name: Deploy Acceptance

on:
  workflow_dispatch:

jobs:
  deploy_acceptance:
    uses: ./.github/workflows/deploy_template.yaml
    permissions: { }
    with:
      clever_cloud_application: 'lunatech-blog-engine-acceptance'
      target_branch: 'acceptance'
      source_branch: 'main'
    secrets: inherit
